USE ROLE AI_ENGINEER;
CREATE SCHEMA IF NOT EXISTS AI_DEVELOPMENT.SI_BOTTLING_COMPANY;
USE SCHEMA AI_DEVELOPMENT.SI_BOTTLING_COMPANY;

-- Create Notebooks
CREATE NOTEBOOK SI_BOTTLING_COMPANY
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Bottling_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        MAIN_FILE = 'SI_BOTTLING_COMPANY.ipynb';
ALTER NOTEBOOK SI_BOTTLING_COMPANY ADD LIVE VERSION FROM LAST;

-- Whether to execute the notebook or not during initial demo setup
{% if EXECUTE_NOTEBOOKS %}
    EXECUTE NOTEBOOK SI_BOTTLING_COMPANY();
{%- endif -%}