USE ROLE AI_ENGINEER;
CREATE SCHEMA IF NOT EXISTS AI_DEVELOPMENT.SI_THE_FOOD_AND_BEVERAGE_COMPANY;
USE SCHEMA AI_DEVELOPMENT.SI_THE_FOOD_AND_BEVERAGE_COMPANY;

-- Create stages for files
CREATE OR REPLACE STAGE DOCUMENTS
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE OR REPLACE STAGE AUDIO
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE OR REPLACE STAGE __DATA
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

-- Copy parquet files into stage
COPY FILES
  INTO @__DATA
  FROM @PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company/data_generation/01_tables/data/;
ALTER STAGE __DATA REFRESH;

-- Copy documents into stages
COPY FILES
  INTO @DOCUMENTS
  FROM @PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company/data_generation/03_documents/data/;
ALTER STAGE DOCUMENTS REFRESH;

-- Create Notebooks
CREATE NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_1_DATA_GENERATION
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_GPU'
        RUNTIME_NAME = 'SYSTEM$GPU_RUNTIME'
        MAIN_FILE = 'SI_THE_FOOD_AND_BEVERAGE_COMPANY_1_DATA_GENERATION.ipynb';
ALTER NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_1_DATA_GENERATION ADD LIVE VERSION FROM LAST;

CREATE NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_2_UNSTRUCTURED_DATA_PART1
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
        RUNTIME_NAME = 'SYSTEM$BASIC_RUNTIME'
        MAIN_FILE = 'SI_THE_FOOD_AND_BEVERAGE_COMPANY_2_UNSTRUCTURED_DATA_PART1.ipynb';
ALTER NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_2_UNSTRUCTURED_DATA_PART1 ADD LIVE VERSION FROM LAST;

CREATE NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_2_UNSTRUCTURED_DATA_PART2
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
        RUNTIME_NAME = 'SYSTEM$BASIC_RUNTIME'
        MAIN_FILE = 'SI_THE_FOOD_AND_BEVERAGE_COMPANY_2_UNSTRUCTURED_DATA_PART2.ipynb';
ALTER NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_2_UNSTRUCTURED_DATA_PART2 ADD LIVE VERSION FROM LAST;

CREATE NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_3_STRUCTURED_DATA
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
        RUNTIME_NAME = 'SYSTEM$BASIC_RUNTIME'
        MAIN_FILE = 'SI_THE_FOOD_AND_BEVERAGE_COMPANY_3_STRUCTURED_DATA.ipynb';
ALTER NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_3_STRUCTURED_DATA ADD LIVE VERSION FROM LAST;

CREATE NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_4_CUSTOM_TOOLS
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
        RUNTIME_NAME = 'SYSTEM$BASIC_RUNTIME'
        MAIN_FILE = 'SI_THE_FOOD_AND_BEVERAGE_COMPANY_4_CUSTOM_TOOLS.ipynb';
ALTER NOTEBOOK SI_THE_FOOD_AND_BEVERAGE_COMPANY_4_CUSTOM_TOOLS ADD LIVE VERSION FROM LAST;