name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.11.*
  - python-dotenv=1.1.0
  - snowflake=1.6.0
  - snowflake-snowpark-python=1.35.0
  - snowflake.core=1.7.0
  - streamlit=1.47.0