USE ROLE AI_ENGINEER;
CREATE OR REPLACE SCHEMA AI_DEVELOPMENT.SI_BIOTECH;
USE SCHEMA AI_DEVELOPMENT.SI_BIOTECH;

-- Create stages for files
CREATE OR REPLACE STAGE DOCUMENTS
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE OR REPLACE STAGE AUDIO
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE OR REPLACE STAGE __DATA
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

-- Copy parquet files into stage
COPY FILES
  INTO @__DATA
  FROM @PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Biotech_Company/data/;
ALTER STAGE __DATA REFRESH;

-- Copy documents into stages
/*COPY FILES
  INTO @DOCUMENTS
  FROM @PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Food_and_Beverage_Company/data_generation/03_documents/data/;
ALTER STAGE DOCUMENTS REFRESH;*/

-- Create Notebooks
CREATE NOTEBOOK SI_BIOTECH_DEMO
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Biotech_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_GPU'
        RUNTIME_NAME = 'SYSTEM$GPU_RUNTIME'
        MAIN_FILE = 'SI_BIOTECH_DEMO.ipynb';
ALTER NOTEBOOK SI_BIOTECH_DEMO ADD LIVE VERSION FROM LAST;