USE ROLE ACCOUNTADMIN;

-- Allow cross-region access for Cortex to access all models
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Create Database for Snowflake Intelligence Agents
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;

-- Use Database for AI Development
USE SCHEMA AI_DEVELOPMENT.PUBLIC;

-- Create a stage for General Custom Tools for Agents
CREATE OR REPLACE STAGE CUSTOM_TOOLS
	DIRECTORY = ( ENABLE = true );

-- Copy code for custom tools into stage
COPY FILES
  INTO @CUSTOM_TOOLS
  FROM @GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/custom_tools/;

-- Create External Access for AI developer
CREATE OR REPLACE NETWORK RULE ai_external_access_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('0.0.0.0:80', '0.0.0.0:443');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ai_external_access_integration
  ALLOWED_NETWORK_RULES = (ai_external_access_rule)
  ENABLED = true;

-- Create an Email integration
CREATE NOTIFICATION INTEGRATION IF NOT EXISTS ai_email_int
  TYPE=EMAIL
  ENABLED=TRUE;

-- Create role for AI engineer
CREATE ROLE IF NOT EXISTS AI_ENGINEER;
GRANT ROLE AI_ENGINEER to USER ADMIN;

-- Grant privileges to AI engineer role
GRANT USAGE, MONITOR, CREATE SCHEMA ON DATABASE AI_DEVELOPMENT TO ROLE AI_ENGINEER;
GRANT ALL ON SCHEMA AI_DEVELOPMENT.PUBLIC TO ROLE AI_ENGINEER;
GRANT READ ON STAGE AI_DEVELOPMENT.PUBLIC.CUSTOM_TOOLS TO ROLE AI_ENGINEER;
GRANT ALL ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU TO ROLE AI_ENGINEER;
GRANT ALL ON COMPUTE POOL SYSTEM_COMPUTE_POOL_GPU TO ROLE AI_ENGINEER;
GRANT ALL ON WAREHOUSE AI_WH TO ROLE AI_ENGINEER;
GRANT USAGE ON INTEGRATION ai_external_access_integration TO ROLE AI_ENGINEER;
GRANT USAGE ON INTEGRATION ai_email_int TO ROLE AI_ENGINEER;

-- Grant privilege to use Cortex Functions
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE AI_ENGINEER;

-- Grant privilege to monitor cortex analyst
GRANT APPLICATION ROLE snowflake.cortex_analyst_requests_admin TO ROLE AI_ENGINEER;

-- Grant privileges to use PyPi packages
GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE AI_ENGINEER;

-- Grant privileges to create agents for Snowflake Intelligence
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE AI_ENGINEER;
GRANT USAGE, CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE AI_ENGINEER;

-- Grant privileges to use GitHub repository
GRANT READ ON GIT REPOSITORY GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS TO ROLE AI_ENGINEER;

-- Setup Custom Tools for Agents
EXECUTE IMMEDIATE FROM @AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/setup_custom_tools.sql;

-- Setup Apps
EXECUTE IMMEDIATE FROM @AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/setup_apps.sql;