USE ROLE ACCOUNTADMIN;
USE SCHEMA AI_DEVELOPMENT.PUBLIC;

CREATE STREAMLIT AI_DEVELOPMENT.PUBLIC.AGENT_CHART_LIBRARY
  FROM @AI_DEVELOPMENT.public.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/apps/agent_charts/
  MAIN_FILE = 'app.py'
  QUERY_WAREHOUSE = AI_WH;

GRANT USAGE ON STREAMLIT AI_DEVELOPMENT.PUBLIC.AGENT_CHART_LIBRARY TO ROLE AI_ENGINEER;